# Base Ditto configuration file
#   You can override these options in custom override files

!Config

  BOT: !Config
    ALLOW_MENTIONS_AS_PREFIX: yes
    PREFIX: '!'
    TOKEN: !ENV BOT_TOKEN
    IGNORE_BOTS: yes
    # INTENTS:  # Map a dictionary of intents

  LOGGING: !Config
    LOG_LEVEL: INFO
    WEBHOOK_URI: ~
  
  DATABASE: !Config
    # Database Settings: Set either a DSN or Hostname, Username, Password and Database
    APPLICATION_NAME: 'Ditto'
    DSN: !ENV POSTGRES_DSN
    HOSTNAME: ~
    USERNAME: ~
    PASSWORD: ~
    DATABASE: ~

  EXTENSIONS:
    # 3rd Party Extensions
    'jishaku': ~

    # Core Extensions
    'cogs.core.admin': ~
    'cogs.core.info': ~

    # Logging Extensions
    'cogs.logging.stats': ~
